apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-aggregator
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aggregator
            image: 961341545391.dkr.ecr.ap-south-1.amazonaws.com/healthsync-aggregator-service:${GITHUB_SHA}
            env:
              - name: AWS_REGION
                value: "ap-south-1"
              - name: CLUSTER_ID
                value: "healthsync-analytics"
              - name: DATABASE
                value: "healthsync_analytics"
              - name: PATIENT_SERVICE_URL
                value: "http://patient-service-router"
              - name: APPOINTMENT_SERVICE_URL
                value: "http://appointment-service-router"
              - name: NOTIFICATION_SERVICE_URL
                value: "http://notification-service-router"
          restartPolicy: OnFailure
