apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-service
      version: blue
  template:
    metadata:
      labels:
        app: appointment-service
        version: blue
    spec:
      containers:
      - name: appointment-service
        image: 961341545391.dkr.ecr.ap-south-1.amazonaws.com/healthsync-appointment-service:${GITHUB_SHA}
        env:
          - name: AWS_DEFAULT_REGION
            value: "ap-south-1"
          - name: AWS_REGION
            value: "ap-south-1"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service-blue
spec:
  type: LoadBalancer
  selector:
    app: appointment-service
    version: blue
  ports:
  - port: 80
    targetPort: 8080
