apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
      version: green
  template:
    metadata:
      labels:
        app: notification-service
        version: green
    spec:
      containers:
      - name: notification-service
        image: 961341545391.dkr.ecr.ap-south-1.amazonaws.com/healthsync-notification-service:${GITHUB_SHA}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-green
spec:
  type: LoadBalancer
  selector:
    app: notification-service
    version: green
  ports:
  - port: 80
    targetPort: 8080
