apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-service
      version: blue
  template:
    metadata:
      labels:
        app: patient-service
        version: blue
    spec:
      containers:
      - name: patient-service
        image: 961341545391.dkr.ecr.ap-south-1.amazonaws.com/healthsync-patient-service:${GITHUB_SHA}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service-blue
spec:
  type: LoadBalancer
  selector:
    app: patient-service
    version: blue
  ports:
  - port: 80
    targetPort: 8080
