apiVersion: v1
kind: Service
metadata:
  name: patient-service-router
spec:
  type: LoadBalancer
  selector:
    app: patient-service
    version: blue
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service-router
spec:
  type: LoadBalancer
  selector:
    app: appointment-service
    version: blue
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-router
spec:
  type: LoadBalancer
  selector:
    app: notification-service
    version: blue
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: aggregator-service-router
spec:
  type: LoadBalancer
  selector:
    app: aggregator-service
    version: blue
  ports:
  - port: 80
    targetPort: 8080
