name: Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push images
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/healthsync-patient-service:$GITHUB_SHA ./patient_record_service
        docker build -t $ECR_REGISTRY/healthsync-appointment-service:$GITHUB_SHA ./appointment_scheduling_service
        docker build -t $ECR_REGISTRY/healthsync-notification-service:$GITHUB_SHA ./notification_service
        docker push $ECR_REGISTRY/healthsync-patient-service:$GITHUB_SHA
        docker push $ECR_REGISTRY/healthsync-appointment-service:$GITHUB_SHA
        docker push $ECR_REGISTRY/healthsync-notification-service:$GITHUB_SHA

    - name: Update kube config
      run: aws eks update-kubeconfig --name healthsync-cluster --region ap-south-1

    - name: Deploy to EKS
      env:
        GITHUB_SHA: ${{ github.sha }}
      run: |
        envsubst < kubernetes/patient-service-blue.yml | kubectl apply -f -
        envsubst < kubernetes/patient-service-green.yml | kubectl apply -f -
        envsubst < kubernetes/appointment-service-blue.yml | kubectl apply -f -
        envsubst < kubernetes/appointment-service-green.yml | kubectl apply -f -
        envsubst < kubernetes/notification-service-blue.yml | kubectl apply -f -
        envsubst < kubernetes/notification-service-green.yml | kubectl apply -f -
        kubectl apply -f kubernetes/router-services.yml
